keys:
  - &abraxas age13n73mqgs2sgwqavprmn80djncc2pzpexxqe53f8jsxq4sadlnd3qcw5esf
  - &shodan age170wzd3m4kld0ctatf0ul0y8p6hlfdphzeyex0ascrw7cqaeqwa6sy786tr
  - &ukko age1pe7gyn74p4dz2p74kqdqqz84zxy35qy7vgkhy7jel8et9p3suflsjl747c
  - &hiisi age19wsx4zq7qccfssx2kejzsqply2l3pw7a23ghs5dmktdwgstpsudq02atz0

creation_rules:
  - path_regex: secrets/users\.yaml$
    key_groups:
      - age:
          - *abraxas
          - *shodan
          - *ukko
          - *hiisi
  - path_regex: secrets/shodan\.yaml$
    key_groups:
      - age:
          - *abraxas
          - *shodan
  - path_regex: secrets/ukko\.yaml$
    key_groups:
      - age:
          - *abraxas
          - *ukko
  - path_regex: secrets/hiisi\.yaml$
    key_groups:
      - age:
          - *abraxas
          - *hiisi
  - path_regex: secrets/abraxas\.yaml$
    key_groups:
      - age:
          - *abraxas
          - *hiisi
